### ISSUE TITLE
Max share shock identification method derivations

### ISSUE THREAD

**Issue by matdehaven** [VFCI/fevdid#7]
Finish max shock identification derivations in the package's list of articles.

[Current draft of the derivation article](https://vfci.github.io/fevdid/articles/derivations.html)

You can also navigate to this from the package website: [https://vfci.github.io/fevdid](https://vfci.github.io/fevdid)
Then "Articles" from the menu bar, and selecting the article.

#### Making Edits
To edit this document, in the repository navigate to `./vignettes/articles/derivations.RMD`.
Once edits are made, you can test them locally by running `devtools::build_site()`.
Once you push the `.RMD` to Github, an action will rebuild the package website hosted on GitHub Pages.

**Comment by matdehaven** [comment]
@fernando-duarte 
I made some progress on the derivations page.  It's more detailed now than what we have in the presentations. 

The time domain section is almost complete, but I would like to add a section discussing using the Choleskey decomposition in the maximization problem.

The frequency domain section is just broad brush strokes.  I'll see if I have time to work on it more this week, but I think it's unlikely.

Feel free to make any edits to the article or add any questions you have here.

I've been working on branch 7-max-share-derivations.

**Comment by fernando-duarte** [comment]
Amazing, thank you, super helpful as I am working on this. I will add if I see anything worth adding.
